# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/75feaecf-58c8-46ed-9d57-f437b5188315";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."disk".device = "/dev/disk/by-uuid/d2b9cea4-a894-4550-ab02-b0d99cc24593";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/91a7c8e7-5aeb-49dc-96c3-77dc06382f2d";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9d486a1e-2655-4d14-9562-c568446821dc"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = "ondemand";
}
