# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=1G" "mode=755" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/91E5-E24E";
    fsType = "vfat";
    options = [ "noauto" "x-systemd.automount" ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/47fa9784-7db5-4b27-9c4c-24bcfe7557f0";
    fsType = "xfs";
  };

  fileSystems."/mnt/hactar" = {
    device = "10.3.0.2:/media/files";
    fsType = "nfs4";
    noCheck = true;
    options = [ "ro" "noauto" "x-systemd.automount" ];
  };

  # Ensure that we have network before trying to do NFS
  systemd.automounts = [{
    after = [ "network-online.target" ];
    wants = [ "network-online.target" "network-pre.target" ];
    wantedBy = [ "display-manager.service" ];
    where = "/mnt/hactar";
  }];

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
