name: Cachix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v17
      - name: Cachix setup
        uses: cachix/cachix-action@v11
        with:
          name: etu
          extraPullNames: "nix-community,fossar"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      # Populate a fake secrets file.
      - name: Populate a fake secrets file
        run: echo '{ mittensFtp.hostname = ""; mittensFtp.user = ""; }' > .data-secrets.nix

      # Build systems.
      - name: Build private-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/private-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system --no-out-link | cachix push etu

      - name: Build work-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/work-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system --no-out-link | cachix push etu

      - name: Build home-server system derivation
        run: nix-build ./deploy.nix -A home-server -I nixpkgs=./nix/nixos-unstable --no-out-link | cachix push etu

      - name: Build vps04 system derivation
        run: nix-build ./deploy.nix -A vps04 -I nixpkgs=./nix/nixos-unstable --no-out-link | cachix push etu

      - name: Build vps05 system derivation
        run: nix-build ./deploy.nix -A vps05 -I nixpkgs=./nix/nixos-unstable --no-out-link | cachix push etu
