name: Cachix

on:
  push:
    branches:
      - main
      - cache

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=./nix/nixos-unstable
          install_url: https://releases.nixos.org/nix/nix-2.3.16/install

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      # Build systems.
      - name: Build private-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/private-laptop/configuration.nix -A system
      - name: Cache private-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build work-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/work-laptop/configuration.nix -A system
      - name: Cache work-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build home-server system derivation
        run: nix-build ./deploy.nix -A home-server
      - name: Cache home-server system derivation
        run: realpath result | cachix push etu

      - name: Build vps04 system derivation
        run: nix-build ./deploy.nix -A vps04
      - name: Cache vps04 system derivation
        run: realpath result | cachix push etu

      - name: Build vps06 system derivation
        run: nix-build ./deploy.nix -A vps06
      - name: Cache vps06 system derivation
        run: realpath result | cachix push etu
