---
name: Cache 📝

'on':
  push:
    branches:
      - main
      - cache

    paths:
      - '**.nix'
      - '**.age'
      - 'flake.lock'

concurrency:
  group: ci-${{ github.ref }}-cache
  cancel-in-progress: true

jobs:
  cache:
    name: Cache 📝
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hostname:
          - laptop-private-elis
          - server-main-elis
          - server-sparv
          - vps04
          - vps06

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - uses: cachix/cachix-action@v14
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      # Build systems.
      - name: Build system derivation
        uses: nick-fields/retry@v3
        with:
          max_attempts: 3
          timeout_minutes: 60
          command: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'
