name: Cachix

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v11
        with:
          name: etu
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      # Build systems.
      - name: Build private-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/private-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system
      - name: Cache private-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build work-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/work-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system
      - name: Cache work-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build home-server system derivation
        run: nix-build ./deploy.nix -A home-server -I nixpkgs=./nix/nixos-unstable
      - name: Cache home-server system derivation
        run: realpath result | cachix push etu

      - name: Build vps04 system derivation
        run: nix-build ./deploy.nix -A vps04 -I nixpkgs=./nix/nixos-unstable
      - name: Cache vps04 system derivation
        run: realpath result | cachix push etu

      - name: Build vps06 system derivation
        run: nix-build ./deploy.nix -A vps06 -I nixpkgs=./nix/nixos-unstable
      - name: Cache vps06 system derivation
        run: realpath result | cachix push etu
