---
name: Check

'on':
  push:
    branches:
      - main

jobs:
  format:
    name: File formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - name: Check nix file formatting
        run: 'nix fmt . -- --check'
      - name: Check yaml file formatting
        run: 'nix run nixpkgs#yamllint -- --strict --format github .'
      - name: Check deadnix file formatting
        run: 'nix run nixpkgs#deadnix -- hosts/ modules/ packages/'
      - name: Check statix file formatting
        run: 'nix run nixpkgs#statix -- check'

  check:
    name: Check flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check the flake
        run: 'nix flake check'
