---
name: Check 🔎

'on':
  push:
    branches:
      - main

    paths:
      - '**.nix'
      - '**.age'
      - 'flake.lock'

jobs:
  check:
    name: Check 🔎
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: DeterminateSystems/nix-installer-action@v9
      - uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: Check the flake
        run: 'nix flake check'
