---
name: Check

'on':
  push:
    branches:
      - main

jobs:
  format:
    name: File formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: cachix/install-nix-action@v22
      - name: Check nix file formatting
        run: 'nix fmt . -- --check'
      - name: Check yaml file formatting
        run: 'nix run nixpkgs#yamllint -- --strict --format github .'
      - name: Check deadnix file formatting
        run: 'nix run nixpkgs#deadnix -- hosts/ modules/ packages/'
      - name: Check statix file formatting
        run: 'nix run nixpkgs#statix -- check'

  check:
    name: Check flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check the flake
        run: 'nix flake check'

  deploy:
    name: Deploy systems
    runs-on: ubuntu-22.04
    needs: check
    # Don't cancel jobs if one job fails
    continue-on-error: true
    strategy:
      matrix:
        hostname:
          - server-main-elis
          - server-sparv
          - vps04
          - vps06

    steps:
      - uses: actions/checkout@v3.6.0
      - uses: cachix/install-nix-action@v22
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Configure SSH key
      - uses: shimataro/ssh-key-action@v2.5.1
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Deploy systems
      - name: Deploy system
        run: 'nix develop -c deploy .#${{ matrix.hostname }}'
