---
name: 'Workflow: Deploy hosts 🚀'

'on':
  workflow_call:
    inputs:
      skipPush:
        required: false
        type: boolean
        default: false
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_KNOWN_HOSTS:
        required: true
      TS_OAUTH_CLIENT_ID:
        required: true
      TS_OAUTH_SECRET:
        required: true

jobs:
  matrix:
    uses: ./.github/workflows/helper_host_matrix.yaml
    with:
      deployOnly: true

  deploy:
    name: 'Deploy ${{ matrix.hostname }} 🚀'
    runs-on: ubuntu-24.04
    needs: matrix
    # Don't cancel jobs if one job fails
    continue-on-error: true
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
      - run: |
          git pull
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: cachix/cachix-action@v16
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      # Build systems.
      - name: 'Build system ${{ matrix.hostname }} 🔨'
        run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'

      # Configure SSH key
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Connect to tailscale
      - uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      # Deploy systems
      - name: 'Deploy host ${{ matrix.hostname }} 🚀'
        run: 'nix develop -c deploy --skip-checks --targets .#${{ matrix.hostname }}'
