---
name: 'Workflow: Check nix flake ❄️'

'on':
  workflow_call:
    inputs:
      skipPush:
        required: false
        type: boolean
        default: false
      branch:
        required: false
        type: string
        default: main
    secrets:
      CACHIX_AUTH_TOKEN:
        required: true

jobs:
  check-nix-flake:
    name: 'Check flake ❄️'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ inputs.branch }}
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: cachix/cachix-action@v16
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: ${{ inputs.skipPush }}

      - name: 'Check flake ❄️'
        run: 'nix flake check'
