---
name: Pull Request

'on':
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build systems
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        hostname:
          - laptop-private-elis
          - server-main-elis
          - server-sparv
          - vps04
          - vps06

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          skipPush: true

      # Build systems.
      - name: Build system derivation
        run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'

  build-shell:
    name: Cache nix shell
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'

      - name: Check the flake
        run: 'nix build .#devShells.x86_64-linux.default'

  check:
    name: Check flake
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4.1.1

      - uses: DeterminateSystems/nix-installer-action@v8
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          skipPush: true

      - name: Check the flake
        run: 'nix flake check'
