---
name: Pull Request

'on':
  pull_request:
    branches:
      - main

jobs:
  format:
    name: File formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Check nix file formatting
        run: 'nix fmt . -- --check'
      - name: Check yaml file formatting
        run: 'nix run nixpkgs#yamllint -- --strict --format github .'
      - name: Check deadnix file formatting
        run: 'nix run nixpkgs#deadnix -- hosts/ modules/ packages/'
      - name: Check statix file formatting
        run: 'nix run nixpkgs#statix -- check --config .statix.toml'

  build:
    name: Build systems
    runs-on: ubuntu-22.04
    needs: format
    strategy:
      matrix:
        hostname:
          - laptop-private-elis
          - server-main-elis
          - server-sparv
          - vps04
          - vps06

    steps:
      - uses: actions/checkout@v4.1.0

      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          skipPush: true

      # Build systems.
      - name: Build system derivation
        run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'

  build-shell:
    name: Cache nix shell
    runs-on: ubuntu-22.04
    needs: format
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'

      - name: Check the flake
        run: 'nix build .#devShells.x86_64-linux.default'

  check:
    name: Check flake
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v4.1.0

      - uses: DeterminateSystems/nix-installer-action@v6
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: 'nix-community'
          skipPush: true

      - name: Check the flake
        run: 'nix flake check'
