---
name: Pull Request

'on':
  pull_request:
    branches:
      - main

jobs:
  matrix:
    uses: ./.github/workflows/helper_host_matrix.yaml

  build-shell:
    uses: ./.github/workflows/helper_cache_shell.yaml
    with:
      skipPush: true

  check-flake:
    uses: ./.github/workflows/helper_check_flake.yaml
    with:
      skipPush: true

  build:
    needs: matrix
    runs-on: ubuntu-24.04
    strategy:
      matrix: ${{ fromJSON(needs.matrix.outputs.matrix) }}
    name: Build ${{ matrix.hostname }} 🔨
    steps:
      - uses: actions/checkout@v4
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: cachix/cachix-action@v16
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true
      - name: Build system
        run: nix build -L ".#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel"
