---
name: 'Pull Request 🔄'

'on':
  pull_request:
    branches:
      - main

jobs:
  build-shell:
    uses: ./.github/workflows/helper_cache_shell.yaml
    with:
      skipPush: true

  check-flake:
    uses: ./.github/workflows/helper_check_flake.yaml
    with:
      skipPush: true
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  build-hosts:
    uses: ./.github/workflows/helper_cache_hosts.yaml
    with:
      skipPush: true
      branch: ${{ github.head_ref }}
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
