name: Update

on:
  schedule:
    - cron: "30 3 * * 1,3,6" # At 03:30 on Monday, Wednesday, and Saturday.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      # Do updates of nixpkgs and other dependencies.
      - name: Update all dependencies
        run: nix-shell --run 'make update-all'
        env:
          NIX_PATH: nixpkgs=./nix/nixos-unstable

      # Build systems.
      - name: Build private-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/private-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system
      - name: Cache private-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build work-laptop system derivation
        run: nix-build '<nixpkgs/nixos>' -I nixos-config=./hosts/work-laptop/configuration.nix -I nixpkgs=./nix/nixos-unstable -A system
      - name: Cache work-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build home-server system derivation
        run: nix-build ./deploy.nix -A home-server -I nixpkgs=./nix/nixos-unstable
      - name: Cache home-server system derivation
        run: realpath result | cachix push etu

      - name: Build vps04 system derivation
        run: nix-build ./deploy.nix -A vps04 -I nixpkgs=./nix/nixos-unstable
      - name: Cache vps04 system derivation
        run: realpath result | cachix push etu

      - name: Build vps06 system derivation
        run: nix-build ./deploy.nix -A vps06 -I nixpkgs=./nix/nixos-unstable
      - name: Cache vps06 system derivation
        run: realpath result | cachix push etu

      - uses: stefanzweifel/git-auto-commit-action@v4.15.3
        with:
          commit_message: "cron(treewide): Upgrade systems"
