---
name: Update

'on':
  schedule:
    - cron: "30 3 * * 1,3,6"  # At 03:30 on Monday, Wednesday, and Saturday.

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          skipPush: true

      # Do updates of nixpkgs and other dependencies.
      - name: Update all dependencies
        run: nix develop --command make update-all
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # Build systems.
      - name: Build laptop-private-elis system derivation
        run: 'nix build .#nixosConfigurations.laptop-private-elis.config.system.build.toplevel'
      - name: Cache private-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build laptop-work-elis system derivation
        run: 'nix build .#nixosConfigurations.laptop-work-elis.config.system.build.toplevel'
      - name: Cache work-laptop system derivation
        run: realpath result | cachix push etu

      - name: Build server-main-elis system derivation
        run: 'nix build .#nixosConfigurations.server-main-elis.config.system.build.toplevel'
      - name: Cache home-server system derivation
        run: realpath result | cachix push etu

      - name: Build vps04 system derivation
        run: 'nix build .#nixosConfigurations.vps04.config.system.build.toplevel'
      - name: Cache vps04 system derivation
        run: realpath result | cachix push etu

      - name: Build vps06 system derivation
        run: 'nix build .#nixosConfigurations.vps06.config.system.build.toplevel'
      - name: Cache vps06 system derivation
        run: realpath result | cachix push etu

      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "cron(treewide): Upgrade systems"
