---
name: Update ⬆️

'on':
  schedule:
    - cron: '30 3 * * 1'  # At 03:30 on Monday.
  workflow_dispatch:

jobs:
  cache-shell:
    uses: ./.github/workflows/helper_cache_shell.yaml
    needs: update

  flake-check:
    uses: ./.github/workflows/helper_check_flake.yaml
    needs: update
    with:
      branch: tmp-updater-branch
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  cache-hosts:
    uses: ./.github/workflows/helper_cache_hosts.yaml
    needs: update
    with:
      branch: tmp-updater-branch
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

  deploy-hosts:
    uses: ./.github/workflows/helper_deploy_hosts.yaml
    needs: promote
    secrets:
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      TS_OAUTH_CLIENT_ID: ${{ secrets.TS_OAUTH_CLIENT_ID }}
      TS_OAUTH_SECRET: ${{ secrets.TS_OAUTH_SECRET }}

  update:
    name: Update dependencies
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: wimpysworld/nothing-but-nix@v6
      - uses: DeterminateSystems/nix-installer-action@v20
      - uses: cachix/cachix-action@v16
        with:
          name: etu
          extraPullNames: 'nix-community'
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Update flake
      - name: Update flake inputs
        run: 'nix flake update'
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # Pre-fetch deps
      - name: Pre-fetch deps
        run: 'nix develop --command true'
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # Do updates of nixpkgs and other dependencies.
      - name: Update all dependencies
        run: 'nix develop --command just update-all'
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # Commit the updated dependencies to temporary branch
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'cron(treewide): Upgrade systems'
          branch: tmp-updater-branch
          push_options: '--force'
          create_branch: true
          skip_fetch: false

  promote:
    name: Promote to main branch
    runs-on: ubuntu-24.04
    needs: [cache-shell, cache-hosts, flake-check]
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main

      - name: Get remote branch data
        run: 'git fetch'

      - name: Get the tmp-updater-branch branch
        run: 'git checkout tmp-updater-branch'

      - name: Push temporary branch to main branch
        run: 'git push origin tmp-updater-branch:main'

      - name: Delete the temporary branch
        run: 'git push origin --delete tmp-updater-branch'
