---
name: Update

'on':
  schedule:
    - cron: "30 3 * * 1,3,6"  # At 03:30 on Monday, Wednesday, and Saturday.

jobs:
  update:
    name: Update dependencies
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18

      # Do updates of nixpkgs and other dependencies.
      - name: Update all dependencies
        run: nix develop --command make update-all
        env:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # Commit the updated dependencies to temporary branch
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "cron(treewide): Upgrade systems"
          branch: tmp-updater-branch
          create_branch: true
          push_options: '--force'

  cache:
    name: Cache system
    runs-on: ubuntu-20.04
    needs: update
    strategy:
      matrix:
        hostname:
          - laptop-private-elis
          - laptop-work-elis
          - server-main-elis
          - vps04
          - vps06

    steps:
      # Clone the code from the temporary branch
      - uses: actions/checkout@v3
        with:
          ref: tmp-updater-branch
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # Build systems.
      - name: Build system derivation
        run: 'nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel'

  check:
    name: Check flake
    runs-on: ubuntu-20.04
    needs: cache
    steps:
      # Clone the code from the temporary branch
      - uses: actions/checkout@v3
        with:
          ref: tmp-updater-branch
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: etu
          extraPullNames: "nix-community"
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Check the flake
        run: 'nix flake check'

  promote:
    name: Promote to main branch
    runs-on: ubuntu-20.04
    needs: check
    steps:
      # Clone the code from the temporary branch
      - uses: actions/checkout@v3
        with:
          ref: tmp-updater-branch

      # Push the changes to the main branch
      - uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          github_token: '${{ secrets.GITHUB_TOKEN }}'
